### ISSUE TITLE
誤字

### ISSUE THREAD

**Issue by MaruyamaKoushirou** [tenon-nonet/Homepage#6]
![IMG_6788](https://github.com/tenon-nonet/Homepage/assets/85824872/76dd0c15-5c2f-45bc-a8c5-561ecafb0d30)
![IMG_6787](https://github.com/tenon-nonet/Homepage/assets/85824872/71251a1d-f014-48ed-a252-744f79064108)
![IMG_6786](https://github.com/tenon-nonet/Homepage/assets/85824872/ab511d12-336b-42f6-b5b6-2ac622e3f807)

**Comment by tenon-nonet** [comment]
誤字結構ありましたね、、指摘ありがとうございます！
次のプッシュの時に修正しておきます👍
